// Export all route setup functions
export { setupKnowledgeListRoute } from './list.route';
export { setupKnowledgeCreateRoute } from './create.route';
export { setupKnowledgeGetRoute } from './get.route';
export { setupKnowledgeUpdateRoute } from './update.route';
export { setupKnowledgeDeleteRoute } from './delete.route';
export { setupKnowledgeCreateLinkRoute } from './create-link.route';
export { setupKnowledgeDeleteLinkRoute } from './delete-link.route';
export { setupKnowledgeGraphObsidianRoute } from './graph-obsidian.route';
export { setupKnowledgeGraphRoute } from './graph.route';
export { setupKnowledgeConvertRoute } from './convert.route';
export { setupKnowledgeConvertBatchRoute } from './convert-batch.route';
export { setupKnowledgeSuggestionsRoute } from './suggestions.route';
export { setupKnowledgeSuggestTagsRoute } from './suggest-tags.route';
export { setupKnowledgeSuggestLinksRoute } from './suggest-links.route';
export { setupKnowledgeTagsRoute } from './tags.route';
export { setupKnowledgeSemanticSearchRoute } from './semantic-search.route';
export { setupKnowledgeAskRoute } from './ask.route';
